[package]
name = "simple-voting"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["you"]

[lib]
path = "src/simple_voting.rs"

[dependencies]
multiversx-sc = "0.63.0"

[dev-dependencies]
num-bigint = "0.4"
multiversx-sc-scenario = "0.63.0"
