[package]
name = "simple-voting-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.simple-voting]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.63.0"
default-features = false
